"""add rating to foods table

Revision ID: cd2f2630c908
Revises: f1bcb73c376d
Create Date: 2024-11-09 20:58:57.824574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd2f2630c908'
down_revision: Union[str, None] = 'f1bcb73c376d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'rating')
    # ### end Alembic commands ###
